CREATE TABLE IF NOT EXISTS favorites (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  city_code VARCHAR(64) NOT NULL,
  label VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_city (user_id, city_code)
);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(64) NOT NULL,
  city_code VARCHAR(64) NOT NULL,
  type ENUM('air', 'water') NOT NULL,
  threshold DECIMAL(5,2) NOT NULL,
  direction ENUM('ABOVE', 'BELOW') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
